import { createContext, useContext, useMemo, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

type Language = 'pt-BR' | 'en-US';

type TranslationMap = Record<string, string>;

type TranslationParams = Record<string, string | number>;

interface LanguageContextType {
  language: Language;
  locale: string;
  setLanguage: (language: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, params?: TranslationParams) => string;
}

const translations: Record<Language, TranslationMap> = {
  'en-US': {
    'app.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.search': 'Search',
    'common.show': 'Show',
    'common.actions': 'Actions',
    'common.status': 'Status',
    'common.stock': 'Stock',
    'common.title': 'Title',
    'common.author': 'Author',
    'common.email': 'Email',
    'common.name': 'Name',
    'common.password': 'Password',
    'common.exportCsv': 'Export CSV',
    'common.exportPdf': 'Export PDF',
    'common.new': 'New',
    'common.noData': 'No data available.',
    'common.firstPage': 'First page',
    'common.previousPage': 'Previous page',
    'common.nextPage': 'Next page',
    'common.lastPage': 'Last page',
    'common.showingRange': 'Showing {start} to {end}',

    'nav.dashboard': 'Dashboard',
    'nav.catalog': 'Catalog',
    'nav.members': 'Members',
    'nav.loans': 'Loans',
    'nav.logout': 'Logout',

    'login.welcome': 'Welcome back',
    'login.subtitle': 'Please enter your credentials to access your account.',
    'login.emailLabel': 'Email or Library ID',
    'login.emailPlaceholder': 'member@libsys.edu',
    'login.passwordLabel': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Forgot Password?',
    'login.signIn': 'Sign In',
    'login.signingIn': 'Signing in...',
    'login.errorInvalid': 'Invalid credentials. Please try again.',
    'login.heroTitle': 'Manage Knowledge.\nSecurely.',
    'login.heroSubtitle': 'Access the world\'s most comprehensive digital library management system designed for modern institutions.',
    'login.version': 'Version 1.0',
    'login.systemHealth': 'System Health: Online',

    'reset.title': 'Reset your password',
    'reset.subtitle': 'You must set a new password to continue.',
    'reset.newPassword': 'New password',
    'reset.currentPassword': 'Current password',
    'reset.currentPasswordPlaceholder': 'Enter your current password',
    'reset.confirmPassword': 'Confirm password',
    'reset.minLengthPlaceholder': 'Minimum 6 characters',
    'reset.repeatPlaceholder': 'Repeat your new password',
    'reset.updatePassword': 'Update password',
    'reset.updating': 'Updating...',
    'reset.errorLength': 'Password must be at least 6 characters.',
    'reset.errorMismatch': 'Passwords do not match.',
    'reset.errorUnable': 'Unable to reset password.',

    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Overview of your library performance, loans, and reports.',
    'dashboard.totalBooks': 'Total Books',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.activeLoans': 'Active Loans',
    'dashboard.overdueLoans': 'Overdue Loans',
    'dashboard.totalFines': 'Total Fines',
    'dashboard.mostBorrowed': 'Most Borrowed Books',
    'dashboard.mostBorrowedSubtitle': 'Top performers by total loans',
    'dashboard.noLoanData': 'No loan data available yet.',
    'dashboard.recentBooks': 'Recently Added Books',
    'dashboard.noBooks': 'No books registered yet.',
    'dashboard.statusAvailable': 'Available',
    'dashboard.statusBorrowed': 'Borrowed',
    'dashboard.errorLoad': 'Unable to load dashboard data.',

    'books.title': 'Book Catalog Management',
    'books.subtitle': 'Manage and track library inventory across all branches.',
    'books.searchTitle': 'Search by title...',
    'books.filterAuthor': 'Filter by author...',
    'books.availability': 'Availability',
    'books.all': 'All',
    'books.available': 'Available',
    'books.borrowed': 'Borrowed',
    'books.addNew': 'Add New Book',
    'books.loading': 'Loading books...',
    'books.noBooks': 'No books found.',
    'books.errorLoad': 'Unable to load books. Please try again.',
    'books.addModalTitle': 'Add New Book',
    'books.bookTitle': 'Book Title',
    'books.bookTitlePlaceholder': 'e.g. The Great Gatsby',
    'books.isbn': 'ISBN',
    'books.author': 'Author',
    'books.authorPlaceholder': 'Author name',
    'books.totalCopies': 'Total Copies',
    'books.saveBook': 'Save Book',

    'users.title': 'User Management',
    'users.subtitle': 'Manage library members, registrations, and account status',
    'users.activeUsers': 'Active Users',
    'users.blockedUsers': 'Blocked Users',
    'users.requiresAttention': 'Requires attention',
    'users.searchPlaceholder': 'Search by Name or Email...',
    'users.loading': 'Loading users...',
    'users.noUsers': 'No users found.',
    'users.userId': 'User ID',
    'users.activate': 'Activate',
    'users.deactivate': 'Deactivate',
    'users.activateUser': 'Activate user',
    'users.deactivateUser': 'Deactivate user',
    'users.resetPassword': 'Reset password',
    'users.registerNewUser': 'Register New User',
    'users.fullName': 'Full Name',
    'users.fullNamePlaceholder': 'Enter full name',
    'users.emailAddress': 'Email Address',
    'users.password': 'Password',
    'users.registerUser': 'Register User',
    'users.errorLoad': 'Unable to load users. Please try again.',
    'users.errorUpdateStatus': 'Unable to update user status. Please try again.',
    'users.errorReset': 'Unable to reset password. Please try again.',
    'users.errorCreate': 'Unable to create user. Please check the form and try again.',
    'users.confirmDeactivate': 'Deactivate {name}? They will lose access until reactivated.',
    'users.confirmActivate': 'Activate {name}?',
    'users.confirmReset': 'Force {name} to reset their password on next login?',
    'users.statusActive': 'Active',
    'users.statusBlocked': 'Blocked',

    'loans.title': 'Active Loans',
    'loans.subtitle': 'Monitor due dates and overdue items.',
    'loans.filterAll': 'All Loans',
    'loans.filterInProgress': 'In Progress',
    'loans.filterActive': 'Active ({count})',
    'loans.filterOverdue': 'Overdue ({count})',
    'loans.filterReturned': 'Returned ({count})',
    'loans.searchPlaceholder': 'Search by member or book...',
    'loans.loading': 'Loading loans...',
    'loans.noLoans': 'No loans found.',
    'loans.errorLoad': 'Unable to load loans. Please try again.',
    'loans.bookDetails': 'Book Details',
    'loans.member': 'Member',
    'loans.dueDate': 'Due Date',
    'loans.action': 'Action',
    'loans.newLoan': 'New Loan',
    'loans.createNewLoan': 'Create New Loan',
    'loans.selectMember': 'Select Member',
    'loans.selectBook': 'Select Book',
    'loans.onlyYourAccount': 'Only your account is eligible',
    'loans.searchMemberPlaceholder': 'Search member by name or email...',
    'loans.searchBookPlaceholder': 'Search by title or author...',
    'loans.loadingMembers': 'Loading members...',
    'loans.loadingBooks': 'Loading books...',
    'loans.searchMembersHint': 'Search by name or email to see results.',
    'loans.searchBooksHint': 'Search by title or author to see results.',
    'loans.noMembers': 'No members found.',
    'loans.noBooksAvailable': 'No available books.',
    'loans.availableCount': '{count} available',
    'loans.selectToContinue': 'Select a member and a book to continue.',
    'loans.loanFor': 'Loan for {member} • {book}',
    'loans.createLoan': 'Create Loan',
    'loans.bookNumber': 'Book #{id}',
    'loans.userNumber': 'User #{id}',
    'loans.memberFallback': 'Member',
    'loans.confirmReturnTitle': 'Confirm Return',
    'loans.confirmReturnMessage': 'Return {book} to close the loan?',
    'loans.confirmReturnButton': 'Confirm Return',
    'loans.confirmRenewalTitle': 'Confirm Renewal',
    'loans.confirmRenewalMessage': 'Renew {book} for another period?',
    'loans.confirmRenewalButton': 'Confirm Renewal',
    'loans.renewLoan': 'Renew loan',
    'loans.returnLoan': 'Return loan',
    'loans.renewing': 'Renewing...',
    'loans.returning': 'Returning...',
    'loans.fine': 'Fine: {amount}',
    'loans.loanReturnedSuccess': 'Loan returned successfully.',
    'loans.loanRenewedSuccess': 'Loan renewed successfully.',
    'loans.errorReturn': 'Unable to return loan. Please try again.',
    'loans.errorRenew': 'Unable to renew loan. Please try again.',
    'loans.errorCreate': 'Unable to create loan. Please try again.',
    'loans.errorOwnAccount': 'You can only create loans for your own account.',
    'loans.errorSelectMemberBook': 'Please select a member and a book.',
    'loans.statusActive': 'Active',
    'loans.statusOverdue': 'Overdue',
    'loans.statusReturned': 'Returned',
    'loans.statusNotReturned': 'In Progress',
    'loans.yesterday': 'Yesterday',
    'loans.today': 'Today',
    'loans.tomorrow': 'Tomorrow',
    'loans.daysAgo': '{count} days ago',
    'loans.inDays': 'In {count} days',
  },
  'pt-BR': {
    'app.loading': 'Carregando...',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Salvar',
    'common.search': 'Buscar',
    'common.show': 'Exibir',
    'common.actions': 'Ações',
    'common.status': 'Status',
    'common.stock': 'Estoque',
    'common.title': 'Título',
    'common.author': 'Autor',
    'common.email': 'Email',
    'common.name': 'Nome',
    'common.password': 'Senha',
    'common.exportCsv': 'Exportar CSV',
    'common.exportPdf': 'Exportar PDF',
    'common.new': 'Novo',
      'common.noData': 'Nenhum dado disponível.',
    'common.firstPage': 'Primeira página',
    'common.previousPage': 'Página anterior',
    'common.nextPage': 'Próxima página',
    'common.lastPage': 'Última página',
    'common.showingRange': 'Mostrando {start} a {end}',

    'nav.dashboard': 'Painel',
    'nav.catalog': 'Catálogo',
    'nav.members': 'Usuários',
    'nav.loans': 'Empréstimos',
    'nav.logout': 'Sair',

    'login.welcome': 'Bem-vindo de volta',
    'login.subtitle': 'Informe suas credenciais para acessar sua conta.',
    'login.emailLabel': 'Email ou ID da biblioteca',
    'login.emailPlaceholder': 'usuario@libsys.edu',
    'login.passwordLabel': 'Senha',
    'login.passwordPlaceholder': '••••••••',
    'login.forgotPassword': 'Esqueceu a senha?',
    'login.signIn': 'Entrar',
    'login.signingIn': 'Entrando...',
    'login.errorInvalid': 'Credenciais inválidas. Tente novamente.',
    'login.heroTitle': 'Gestão do conhecimento.\nCom segurança.',
    'login.heroSubtitle': 'Acesse o sistema de gestão de bibliotecas digitais mais completo, pensado para instituições modernas.',
    'login.version': 'Versão 1.0',
    'login.systemHealth': 'Status do sistema: Online',

    'reset.title': 'Redefina sua senha',
    'reset.subtitle': 'Você precisa definir uma nova senha para continuar.',
    'reset.newPassword': 'Nova senha',
    'reset.currentPassword': 'Senha atual',
    'reset.currentPasswordPlaceholder': 'Digite sua senha atual',
    'reset.confirmPassword': 'Confirmar senha',
    'reset.minLengthPlaceholder': 'Mínimo de 6 caracteres',
    'reset.repeatPlaceholder': 'Repita sua nova senha',
    'reset.updatePassword': 'Atualizar senha',
    'reset.updating': 'Atualizando...',
    'reset.errorLength': 'A senha deve ter pelo menos 6 caracteres.',
    'reset.errorMismatch': 'As senhas não coincidem.',
    'reset.errorUnable': 'Não foi possível redefinir a senha.',

    'dashboard.title': 'Painel',
    'dashboard.subtitle': 'Visão geral do desempenho da biblioteca, empréstimos e relatórios.',
    'dashboard.totalBooks': 'Total de livros',
    'dashboard.totalUsers': 'Total de usuários',
    'dashboard.activeLoans': 'Empréstimos ativos',
    'dashboard.overdueLoans': 'Empréstimos atrasados',
    'dashboard.totalFines': 'Multas totais',
    'dashboard.mostBorrowed': 'Livros mais emprestados',
    'dashboard.mostBorrowedSubtitle': 'Destaques por total de empréstimos',
    'dashboard.noLoanData': 'Nenhum dado de empréstimo disponível.',
    'dashboard.recentBooks': 'Livros adicionados recentemente',
    'dashboard.noBooks': 'Nenhum livro cadastrado ainda.',
    'dashboard.statusAvailable': 'Disponível',
    'dashboard.statusBorrowed': 'Emprestado',
    'dashboard.errorLoad': 'Não foi possível carregar o painel.',

    'books.title': 'Gestão do catálogo',
    'books.subtitle': 'Gerencie e acompanhe o acervo em todas as unidades.',
    'books.searchTitle': 'Buscar por título...',
    'books.filterAuthor': 'Filtrar por autor...',
    'books.availability': 'Disponibilidade',
    'books.all': 'Todos',
    'books.available': 'Disponível',
    'books.borrowed': 'Emprestado',
    'books.addNew': 'Adicionar livro',
    'books.loading': 'Carregando livros...',
    'books.noBooks': 'Nenhum livro encontrado.',
    'books.errorLoad': 'Não foi possível carregar os livros. Tente novamente.',
    'books.addModalTitle': 'Adicionar livro',
    'books.bookTitle': 'Título do livro',
    'books.bookTitlePlaceholder': 'ex.: O Grande Gatsby',
    'books.isbn': 'ISBN',
    'books.author': 'Autor',
    'books.authorPlaceholder': 'Nome do autor',
    'books.totalCopies': 'Total de cópias',
    'books.saveBook': 'Salvar livro',

    'users.title': 'Gestão de usuários',
    'users.subtitle': 'Gerencie membros, cadastros e status das contas',
    'users.activeUsers': 'Usuários ativos',
    'users.blockedUsers': 'Usuários bloqueados',
    'users.requiresAttention': 'Requer atenção',
    'users.searchPlaceholder': 'Buscar por nome ou email...',
    'users.loading': 'Carregando usuários...',
    'users.noUsers': 'Nenhum usuário encontrado.',
    'users.userId': 'ID do usuário',
    'users.activate': 'Ativar',
    'users.deactivate': 'Desativar',
    'users.activateUser': 'Ativar usuário',
    'users.deactivateUser': 'Desativar usuário',
    'users.resetPassword': 'Redefinir senha',
    'users.registerNewUser': 'Cadastrar novo usuário',
    'users.fullName': 'Nome completo',
    'users.fullNamePlaceholder': 'Informe o nome completo',
    'users.emailAddress': 'Endereço de email',
    'users.password': 'Senha',
    'users.registerUser': 'Cadastrar usuário',
    'users.errorLoad': 'Não foi possível carregar os usuários. Tente novamente.',
    'users.errorUpdateStatus': 'Não foi possível atualizar o status do usuário. Tente novamente.',
    'users.errorReset': 'Não foi possível redefinir a senha. Tente novamente.',
    'users.errorCreate': 'Não foi possível criar o usuário. Verifique o formulário e tente novamente.',
    'users.confirmDeactivate': 'Desativar {name}? Ele perderá o acesso até ser reativado.',
    'users.confirmActivate': 'Ativar {name}?',
    'users.confirmReset': 'Forçar {name} a redefinir a senha no próximo login?',
    'users.statusActive': 'Ativo',
    'users.statusBlocked': 'Bloqueado',

    'loans.title': 'Empréstimos ativos',
    'loans.subtitle': 'Monitore prazos e itens em atraso.',
    'loans.filterAll': 'Todos os empréstimos',
    'loans.filterInProgress': 'Em andamento',
    'loans.filterActive': 'Ativos ({count})',
    'loans.filterOverdue': 'Atrasados ({count})',
    'loans.filterReturned': 'Devolvidos ({count})',
    'loans.searchPlaceholder': 'Buscar por membro ou livro...',
    'loans.loading': 'Carregando empréstimos...',
    'loans.noLoans': 'Nenhum empréstimo encontrado.',
    'loans.errorLoad': 'Não foi possível carregar os empréstimos. Tente novamente.',
    'loans.bookDetails': 'Detalhes do livro',
    'loans.member': 'Membro',
    'loans.dueDate': 'Devolução',
    'loans.action': 'Ação',
    'loans.newLoan': 'Novo empréstimo',
    'loans.createNewLoan': 'Criar empréstimo',
    'loans.selectMember': 'Selecionar membro',
    'loans.selectBook': 'Selecionar livro',
    'loans.onlyYourAccount': 'Apenas sua conta está disponível',
    'loans.searchMemberPlaceholder': 'Buscar membro por nome ou email...',
    'loans.searchBookPlaceholder': 'Buscar por título ou autor...',
    'loans.loadingMembers': 'Carregando membros...',
    'loans.loadingBooks': 'Carregando livros...',
    'loans.searchMembersHint': 'Busque por nome ou email para ver resultados.',
    'loans.searchBooksHint': 'Busque por título ou autor para ver resultados.',
    'loans.noMembers': 'Nenhum membro encontrado.',
    'loans.noBooksAvailable': 'Nenhum livro disponível.',
    'loans.availableCount': '{count} disponíveis',
    'loans.selectToContinue': 'Selecione um membro e um livro para continuar.',
    'loans.loanFor': 'Empréstimo para {member} • {book}',
    'loans.createLoan': 'Criar empréstimo',
    'loans.bookNumber': 'Livro #{id}',
    'loans.userNumber': 'Usuário #{id}',
    'loans.memberFallback': 'Membro',
    'loans.confirmReturnTitle': 'Confirmar devolução',
    'loans.confirmReturnMessage': 'Devolver {book} para encerrar o empréstimo?',
    'loans.confirmReturnButton': 'Confirmar devolução',
    'loans.confirmRenewalTitle': 'Confirmar renovação',
    'loans.confirmRenewalMessage': 'Renovar {book} por mais um período?',
    'loans.confirmRenewalButton': 'Confirmar renovação',
    'loans.renewLoan': 'Renovar empréstimo',
    'loans.returnLoan': 'Devolver empréstimo',
    'loans.renewing': 'Renovando...',
    'loans.returning': 'Devolvendo...',
    'loans.fine': 'Multa: {amount}',
    'loans.loanReturnedSuccess': 'Empréstimo devolvido com sucesso.',
    'loans.loanRenewedSuccess': 'Empréstimo renovado com sucesso.',
    'loans.errorReturn': 'Não foi possível devolver o empréstimo. Tente novamente.',
    'loans.errorRenew': 'Não foi possível renovar o empréstimo. Tente novamente.',
    'loans.errorCreate': 'Não foi possível criar o empréstimo. Tente novamente.',
    'loans.errorOwnAccount': 'Você só pode criar empréstimos para sua própria conta.',
    'loans.errorSelectMemberBook': 'Selecione um membro e um livro.',
    'loans.statusActive': 'Ativo',
    'loans.statusOverdue': 'Atrasado',
    'loans.statusReturned': 'Devolvido',
    'loans.statusNotReturned': 'Em andamento',
    'loans.yesterday': 'Ontem',
    'loans.today': 'Hoje',
    'loans.tomorrow': 'Amanhã',
    'loans.daysAgo': '{count} dias atrás',
    'loans.inDays': 'Em {count} dias',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language') as Language | null;
    return stored === 'pt-BR' || stored === 'en-US' ? stored : 'pt-BR';
  });

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (next: Language) => {
    setLanguageState(next);
    localStorage.setItem('language', next);
  };

  const toggleLanguage = () => {
    setLanguage(language === 'pt-BR' ? 'en-US' : 'pt-BR');
  };

  const t = (key: string, params?: TranslationParams) => {
    const template = translations[language][key] ?? key;
    if (!params) return template;
    return template.replace(/\{(\w+)\}/g, (_, token: string) => String(params[token] ?? `{${token}}`));
  };

  const value = useMemo(() => ({
    language,
    locale: language,
    setLanguage,
    toggleLanguage,
    t,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
