"""add_fine_amount_to_loans

Revision ID: 625aad62190d
Revises: 3848eb151dd1
Create Date: 2026-02-04 03:29:47.680766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625aad62190d'
down_revision: Union[str, Sequence[str], None] = '3848eb151dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default="0"))   
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'fine_amount')
    # ### end Alembic commands ###
